### PR TITLE
Add a root Makefile and setup.py to install everything easily

### PR DESCRIPTION
**Pull request by stacyharper**
With those it become easy to package the project: https://git.sr.ht/~stacyharper/personal-aports/tree/main/item/stacy/celeste-magic-timer/APKBUILD

### CODE REVIEW

**Comment by rhelmot** [comment]
distutils is hilariously deprecated (removed in python 3.12!), can you swap it for setuptools?

**Comment by stacyharper** [comment]
> distutils is hilariously deprecated (removed in python 3.12!), can you swap it for setuptools?

Ah okay. Sorry my Python is a bit outdated :) Done!

**Comment by stacyharper** [comment]
I added a commit to enforce the modules to be installed in a dedicated folder, so that everything does't stay in the common `site-packages/` folder. For this to works, I had to use relative imports for the module to importe themselves correctly.

**Comment by rhelmot** [comment]
I know this is just me being anal, but it's considered a faux pas to have both capital letters and underscores in python package names. Can you name the package `celeste_magic_timer`?

This isn't something I think is a good idea for right now, but we may want to make the tracer build and distribute as part of the python package.

**Comment by stacyharper** [comment]
aha np it is your project so it's normal to wish the best :)

Done!

**Review by rhelmot — APPROVED** [review]

**Comment by rhelmot** [comment]
Merged. Thank you so much!

**Pull request merged**
