### PR TITLE
Add event.py to trigger commands on events

### PR DESCRIPTION
**Pull request by stacyharper**
First, thank for this project! 

I'm working on a live split program called Splitter: https://sr.ht/~stacyharper/splitter/

I'd like to use this project to trigger commands to my external program, and a simple way for this is to bind hook commands directly.

I added two callbacks even if I need one command on "forward", because I think it is more generic and would fit with more use cases.

### CODE REVIEW

**Comment by rhelmot** [comment]
This change seems correct, but I'm not sure it's in the spirit of the project. The tracer is meant to be the most generic component imaginable, and this is adding some behavior for a very specific condition. Can I hear about what kind of project structure you're working with that it's not feasible to poll the dumped autositter info file like the rest of CelesteMagicTimer?

**Comment by stacyharper** [comment]
Yes another approach would be for me to write a third program that would track the autosplitterinfo, read it, understand it, then trigger some commands. But I thought it was easier, and still generic enough, to hook this from the tracer itself.

But I agree with you that the hook we would implement here have to be generic enough for most use cases. And I could write some other hooks to cover most cases if needed (ex: cinematic start/stop).

I will definitely not implement this from Splitter itself, that is a generic speedrun tool, and that already offer cli commands to hook action from outside.

**Comment by rhelmot** [comment]
Have you looked into the [AutoSplitterInfo python class](https://github.com/rhelmot/CelesteMagicTimer/blob/main/timer/celeste_timer.py#L143)? That seems fairly independent from being a speedrun tool. I would totally accept a `event.py` script which imports AutoSplitterInfo and could be configured from the command line to run commands on certain events - we could put as many events as we wanted into that!

**Comment by stacyharper** [comment]
I'm okay with this. I wrote `event.py` and added those two hooks. We could add more if needed.

**Comment by rhelmot** [comment]
Amazing, thank you!

**Pull request merged**
